# Generated by Django 5.2.6 on 2026-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_external_patient_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='firebase_user_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
